### ISSUE TITLE
pyc files are not needed if including source py files

### ISSUE THREAD

**Issue by hoover900** [Viele/onionSkinRenderer#1]
pyc are compiled versions of the py files. you may run into issues by including them.

https://coderwall.com/p/wrxwog/why-not-to-commit-pyc-files-into-git-and-how-to-fix-if-you-already-did

**Comment by Viele** [comment]
thanks for the info. I didn't know that. I'll just remove them with the next commit

**Comment by Viele** [comment]
removed with latest commit
