### ISSUE TITLE
maya2016.5 dx testing, replacing object showing previous object ghost, issue

### ISSUE THREAD

**Issue by alfsici** [Viele/onionSkinRenderer#12]
Currently testing it on maya 2016.5, using the DirectX latest version , i noticed that if i replace the onion object it shows a ghost of the previously object in the scene (seems to keep the previous goemetry still in memory) .

Steps to reproduce:
1. lunch the onion UI, add an object, switch to OnionViewport , turn on visualize for a few ghosting frames (WORKS)
2. remove first object ,and clear buffer , no objects being ghosted ( WORKS)
3. add any other object in the scene to the Onion Object, now i see the previously removed object and the new object being ghosted. (not working)

The only way it seems to be able to show the correct ghosting after this 3 steps, it seems that i have to close the UI, re launch the script , add object in.

**Comment by Viele** [comment]
thanks for the detailed bug description. Made it a lot easier to track down
fixed :)

**Comment by alfsici** [comment]
Thank you @Viele , amazing fast response!
