### ISSUE TITLE
Tint option into global Opacity slider.

### ISSUE THREAD

**Issue by alfsici** [Viele/onionSkinRenderer#13]
I am finding myself trying to turn down globally the opacity for all the onion skins, alto once you have 10 layers to manage it gets quite tedious (and perhaps these are not fading nicely anymore), so i was wondering if the slider that changes the Tint color instead could be turned to change the global opacity for all the onions, so the user could globally make them more visually prominent or less visible in the viewport.
Changing the tint could still be done by simply changing the colors of pre and post, so i don't see it as a big loss.

**Comment by Viele** [comment]
global opacity slider added, tint remains.
Let me know what you think of the ui position

**Comment by alfsici** [comment]
Im loving it!! 
Thank you again!
