### ISSUE TITLE
excuse me,how to install this?

### ISSUE THREAD

**Issue by gccbs01002** [Viele/onionSkinRenderer#16]
i followed the tutorial and pasted these files.
however i can not see any new ui setting in maya.
can you teach me more detail things to install this,please.

**Comment by Viele** [comment]
hello there

sorry for the late response but I wasn't actively developing this tool for a while.
For instructions on how to install please see my introduction on vimeo: https://vimeo.com/259565212

If you have any questions beyond that feel free to write me an email: chris.lenden@gmail.com
