### ISSUE TITLE
support for Dx11 and OpenGL

### ISSUE THREAD

**Issue by Viele** [Viele/onionSkinRenderer#8]
Only supporting OpenGLCore is a problem for some studios

**Comment by Viele** [comment]
implemented

**Comment by alfsici** [comment]
Hi @Viele , thank you for this update(much appreciated!), i was wondering if this is also being updated for the maya 2016 version?

**Comment by Viele** [comment]
i am working on it just now. But I'll bring the 2017 version to a stable release first and then I'll port it back to 2016

**Comment by Viele** [comment]
2016 is now up and running. If you encounter any problems please just open an issue ;)

**Comment by alfsici** [comment]
Seems to work Great!Will keep on testing it for a little longer! THANK YOU!
